services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "app_user"
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "app_password"
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com" # Ersetzen Sie dies durch Ihre E-Mail
      PGADMIN_DEFAULT_PASSWORD: "catsarecool" # Ersetzen Sie dies durch ein sicheres Passwort
    ports:
      - "5050:80"
    networks:
      - postgres-network
    depends_on:
      - db

volumes:
  postgres-data:


networks:
  postgres-network:
    driver: bridge
