version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    network_mode: bridge

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - 5432:5432

volumes:
  postgres-data:
